### ISSUE TITLE
Debian packaging

### ISSUE THREAD

**Issue by adrelanos** [anthraxx/linux-hardened#10]
Could you please provide a Debian package? And/or a `/debian` packaging folder?

Not necessarily for packages.debian.org. Also a third party deb would be good.

I don't know how realistic such a request is. But I also hope to find out...

Did anyone run this kernel on Debian (buster) yet, what were your experiences? Anyone has any instructions for this?

**Comment by Bernhard40** [comment]
IMO packaging is some downstream job. Here are only pure kernel sources which are distro agnostic. Anyway adding one more patch to debian kernels should be trivial to do.

**Comment by anthraxx** [comment]
We are only providing sources here, there won't be any precompiled versions of the hardened kernel available. I'm just also an Arch Linux packager, but that doesn't mean we want to provide official precompiled releases

**Comment by egberts** [comment]
works for me on Devuan (Debian 11 variant but without `systemd`).

I cannot state whether this kernel works with systemd or not (I am guessing, not).
