### ISSUE TITLE
Why is "CONFIG_DEVMEM=n"?

### ISSUE THREAD

**Issue by Utini2000** [anthraxx/linux-hardened#11]
Hello everyone, 
I am trying to run "throttled" also known as "lenovo-throttling-fix" and it won't work because it needs "CONFIG_DEVMEM=y". 
I wonder why linux-hardened as set it to "CONFIG_DEVMEM=n" and if there is a chance it could be changed to "CONFIG_DEVMEM=y"?

Thanks in advance!

**Comment by anthraxx** [comment]
It is disabled by default as it allows direct physical memory access and is not required for general use. Security and cutting attack surface is prioritized over additional optional features that only a marginal userbase would benefit from.
You can compile your own variant if you really want to have it enabled and see if your use case works with
```
CONFIG_STRICT_DEVMEM=y CONFIG_IO_STRICT_DEVMEM=y
```

**Comment by Utini2000** [comment]
Well I tried several packages now that can modify the TDP/Power limit and they all won't work with linux-hardened.

Is there a way to make an exception for one specific package? e.g. have it disabled systemwide except for that one package?

**Comment by anthraxx** [comment]
I'm sorry, it is not possible to limit the usage to a specific application without exposing the surface in general. You either need to compile your own kernel or live without such applications.

**Comment by Utini2000** [comment]
Alright :( Thanks for your quick support!

**Comment by Bernhard40** [comment]
After LOCKDOWN will be upstreamed and enabled here it may be possible to use:
```
CONFIG_DEVMEM=y
CONFIG_STRICT_DEVMEM=y
CONFIG_IO_STRICT_DEVMEM=y
```
as DEVMEM will be protected by LOCKDOWN and the latter can be disabled o runtime without kernel recompilation.

**Comment by anthraxx** [comment]
Yes, but it would still (kind of, at least partially) mean to switch off hardened by toggling lockdown at runtime and is still nothing that can e limited to a specific application.

**Comment by anthraxx** [comment]
I'm closing this issue for now, as devmem will remain off by default for now. LOCKDOWN can't easily be enable by default to protect devmem by default as the implication with out-of-tree modules like dkms are not feasible for a huge margin of the desktop user base. On server systems lockdown can easily be enabled if no dkms modules are needed and such environments in average don't need devmem either.
Hence the conclusion to keep LOCKDOWN disabled by default and therefor keep devmem disabled as well.
