### ISSUE TITLE
Checksum for config on AUR invalid

### ISSUE THREAD

**Issue by cawilliamson** [anthraxx/linux-hardened#12]
Hey there!

Awesome work on the kernel - just one quick thing - your AUR package has an invalid checksum for the file `config.x86_64` on your `linux-hardened-git` package.

Would be awesome if you could fix it - sadly my hardware requires 5.3+ so I'm itching to get a hardened kernel built and installed for it. :)

Thanks

**Comment by anthraxx** [comment]
for AUR related things, please write to the AUR package comments next time.
the git package will soon switch to 5.4-rc as in the following days i gonna start tagging 5.3 officially
