### ISSUE TITLE
List of software that won't work with linux-hardened

### ISSUE THREAD

**Issue by Utini2000** [anthraxx/linux-hardened#13]
Hey there,
I have been using linux-hardened for ~2 years now but lately I am finding more and more packages/software that won't work with linux-hardened due to missing/disabled options.

I thought it might be a good idea to list those packages somewhere here so that other ppl are aware of it and won't to troubleshoot for ages (like I did).

**Popular packages for example are:**
skype
skypeforlinux
throttled
lenovo-throttle-fix

**Comment by anthraxx** [comment]
It's not really technically an incompatibility with this kernel but with the config shipped or used. I don't think it's particularly a good place to collect a list own downstream applications with issue, even when the recommended configs result in certain unusable applications.

**Comment by Utini2000** [comment]
The config is part of this kernel, in fact it is the main thing that makes this kernel different from the standard linux kernel. So I would think that an incompatibility with the kernels config is comperable to an incompatibility with the kernel?

I wouldn't list any applications that are already unusable with the linux kernel but only applications that work with linux but not with linux-hardened.

**Comment by tsautereau-anssi** [comment]
> The config is part of this kernel

No. Although several patches in linux-hardened change defaults for Kconfig options or add a few ones to adjust sysctl default values, the config is done separately by people compiling/packaging the kernel. In the case of Arch Linux, that's @anthraxx. You can use [ABS](https://wiki.archlinux.org/index.php/Arch_Build_System) (or just clone this repository) to compile linux-hardened with your own config. This repository contains the linux-hardened kernel sources and has no relation with any Linux distro.

> in fact it is the main thing that makes this kernel different from the standard linux kernel.

Wrong. Take a look at the commits.

**Comment by anthraxx** [comment]
You mean besides all the functional changes, canary additions, slab verification and other features?
Config is just config, I do not plan to track a userspace list here
