### ISSUE TITLE
Zombieload V2 - Do we need to disable hyperthread or is linux-hardened safe?

### ISSUE THREAD

**Issue by Utini2000** [anthraxx/linux-hardened#15]
Hi there,

with the recent Zombieload V2 issue I wonder if it would be a good idea to disable hyperthread on Intel CPU's or if users of linux-hardened safe? 

From my understanding linux-hardened user are safe in regards to all the previous security risks (spectre,meltdown,...)?

Thanks!

**Comment by tsautereau-anssi** [comment]
The linux-hardened patch set does not add any particular mitigation to what is already provided by mainline as far as CPU vulnerabilities (Meltdown, Spectre, SSB, L1TF, MDS, TAA, etc.) are concerned.

As for disabling Intel's Hyper-threading, this **can** indeed be part of the mitigations required to correctly address the TSX Asynchronous Abort (TAA) Intel CPU vulnerability (what you called _Zombieload V2_). You can enable these mitigations by adding  ``tsx_async_abort=full,nosmt`` to your kernel command line.
This is only needed on Intel systems that are not vulnerable to MDS or that are already deploying complete mitigations against it (``mds=full,nosmt``). On such systems, an alternative is to disable TSX by adding ``tsx=off`` on your command line.

Finally, keep in mind that these mitigations require a CPU microcode update. You can read more about all that [here](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/Documentation/admin-guide/hw-vuln/tsx_async_abort.rst?h=v5.3.11) and [here](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/Documentation/x86/tsx_async_abort.rst?h=v5.3.11).

**Comment by anthraxx** [comment]
Above mentioned cmdline arguments override the kernel detection. In most cases it should be sufficient to have `CONFIG_X86_INTEL_TSX_MODE_AUTO=y` in your kconfig (which also does require an up to date microcode), it should select the appropriate mitigation itself.
But if you want to be sure, you can of cause disable or force mitigation via cmdline (like @tsautereau-anssi showed) or simply use `CONFIG_X86_INTEL_TSX_MODE_OFF` to have it turned off without cmdline fiddling.
An HTML rendered variant of above doc: https://www.kernel.org/doc/html/latest/admin-guide/hw-vuln/tsx_async_abort.html
