### ISSUE TITLE
5.3.12 fails on slub.c

### ISSUE THREAD

**Issue by karesmakro** [anthraxx/linux-hardened#18]
Hello there,
the latest patch 5.3.12 is failing on slub.c:

mm/slub.c: In function ‘slab_free_freelist_hook’:
mm/slub.c:1513:5: error: expected ‘while’ before ‘else’
   } else if (s->ctor) {
     ^~~~
mm/slub.c:1476:8: warning: unused variable ‘old_tail’ [-Wunused-variable]
  void *old_tail = *tail ? *tail : *head;
        ^~~~~~~~
mm/slub.c:1525:2: warning: no return statement in function returning non-void [-Wreturn-type]
  } while (object != old_tail);
  ^
mm/slub.c: At top level:
mm/slub.c:1525:4: error: expected identifier or ‘(’ before ‘while’
  } while (object != old_tail);
    ^~~~~
mm/slub.c:1527:2: error: expected identifier or ‘(’ before ‘if’
  if (*head == *tail)
  ^~
mm/slub.c:1530:2: error: expected identifier or ‘(’ before ‘return’
  return *head != NULL;
  ^~~~~~
mm/slub.c:1531:1: error: expected identifier or ‘(’ before ‘}’ token
 }
 ^
make[4]: *** [scripts/Makefile.build:281: mm/slub.o] Fehler 1

**Comment by anthraxx** [comment]
A test patch change related to KASAN and slab poisoning slipped into the branch and thereby the release, sorry for that. Updates to the stable variant, that patch change was planned for testing and not releasing >.>
