### ISSUE TITLE
Latest patch (4.19.7.a) breaks X1C6 LED Audio Indicators

### ISSUE THREAD

**Issue by codebam** [anthraxx/linux-hardened#2]
The latest patch (4.19.7.a) broke the LED audio indicators on my X1 Carbon 6th Gen which were working fine on the 4.19.6.a patch. This issue is also not present on the vanilla kernel 4.19.7.a.

Running Arch Linux with the patch applied through the `linux-hardened` package in `extra`

**Comment by anthraxx** [comment]
Any chance you are up for a bisect between v4.19.7 and HEAD? That would make it easier

**Comment by codebam** [comment]
@anthraxx if you can tell me what I need to do sure? I'm not sure how to properly do that

**Comment by codebam** [comment]
Last update (4.19.10.a-1-hardened) fixed the audio LED indicators and they are working now

**Comment by anthraxx** [comment]
@codebam perfect, thanks for the feedback. next time i provide you some guidance how to bisect it properly. Pre xmas time schedule is taught :smile:

**Comment by codebam** [comment]
Thanks! :smiley:
