### ISSUE TITLE
Why 32bit kernels removed from Parabola distribution?

### ISSUE THREAD

**Issue by aprokopyev** [anthraxx/linux-hardened#38]
Hello,

It seems a month ago 686 kernels were still present:
https://archive.fo/9eQBN

What happened? Can I still build and use them manually?
What about Debian and Devuan? Is your kernel compatible with ZFS? Is ZFS pool safe if using your kernel?

The same about armv7hf 32bit ?

**Comment by madaidan** [comment]
linux-hardened was never meant to support 32-bit AFAIK.

https://github.com/AndroidHardeningArchive/linux-hardened/wiki/Out-of-scope-features

> * architecture-specific features outside of x86_64 and arm64 (either legacy or too niche)

You can still use the arch-independent features and besides, what your distro does is irrelevant to this repo.

**Comment by Megver83** [comment]
Parabola kernels maintainer here. The linux-libre-xtreme kernel was removed because linux-libre-hardened became the same. Plus, this is a question you should have done in the Parabola mailing list or forum, not here.

Plus, just read the description of this repo:
> archs other than multiarch arm64 / x86_64 aren't in scope

**Comment by 8573** [comment]
> Is your kernel compatible with ZFS?

linux-hardened with ZFS works well for me (using the distribution NixOS).

**Comment by aprokopyev** [comment]
> > Is your kernel compatible with ZFS?
> 
> linux-hardened with ZFS works well for me (using the distribution NixOS).

Please let me know, is it possible to use NixOS without systemD? 
I know there is GUIX distribution with shepherd init system, but I would prefer OpenRC and GUIX package syntax looks for me too drastically lisp like :)

**Comment by aprokopyev** [comment]
What is it:
https://nixos.org/nixos/manual/options.html#opt-services.certmgr.svcManager
?

**Comment by 8573** [comment]
> What is it:
> https://nixos.org/nixos/manual/options.html#opt-services.certmgr.svcManager

I suppose it is what the documentation says, a configuration option for some Cloudflare certificate management tool.  Probably a more appropriate place for Nix questions is <https://github.com/NixOS/nixpkgs/issues>.

**Comment by anthraxx** [comment]
Closing as this are questions related to downstream consumers :cat:
