### ISSUE TITLE
Deb packages

### ISSUE THREAD

**Issue by HulaHoop0** [anthraxx/linux-hardened#42]
Hi. Can you please consider creating debs in an apt repo for releases? This would increase uptake and make the kernel readily usable by downstream distros like us (Whonix). Also when new security fixes are made it will be much faster to get a newer version out for the masses.

As far as security goes, everyone will be using auditable and signed builds (if you're using reproducible build infrastructure) that will greatly reduce attacks against dev machines by nefarious actors.

**Comment by anthraxx** [comment]
For the time being there are no plans to provide pre built variants of this projects in an apt repository. Maybe at a later point when i setup github sponsors and get a bit of funding that allows me to invest more time, but right now this is not feasible as it would also add a lot of non core hardened related time investment like general purpose feature Kconfig change requests and all sort of other time consuming problems.
I'm not saying this won't happen, but right now I simply cannot provide additional non core development time for pre built distribution.
