### ISSUE TITLE
general protection fault on 5.6.16

### ISSUE THREAD

**Issue by karesmakro** [anthraxx/linux-hardened#43]
Since latest kernel 5.6.16 with linux-hardened patchset and xtables Kernel module I get a general protection fault.
OS: Debian 9 and Ubuntu 16.04 / guest in a KVM environment
gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1)

It seems that this happens, if the server recieves a special packet. I'm also using the kernel lockdown function

Here is the output:
`Jun  4 22:32:45 kernel: [   18.475324] general protection fault, probably for non-canonical address 0x8030000000000000: 0000 [#1] SMP PTI
Jun  4 22:32:45 kernel: [   18.475364] CPU: 1 PID: 1675 Comm: W-Q0 Not tainted 5.6.16-default #1
Jun  4 22:32:45 kernel: [   18.475383] Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS 1.10.2-1 04/01/2014
Jun  4 22:32:45 kernel: [   18.475415] RIP: 0010:0xffffffffc06b4f00
Jun  4 22:32:45 kernel: [   18.475433] Code: 01 00 00 48 8b 83 b8 00 00 00 48 85 c0 0f 84 ce 00 00 00 0f b6 10 84 d2 0f 84 c3 00 00 00 48 01 d0 0f 84 ba 00 00 00 48 8b 00 <f6> 80 84 00 00 00 01 0f 84 aa 00 00 00 0f b7 43 32 66 83 f8 02 0f
Jun  4 22:32:45 kernel: [   18.475495] RSP: 0018:ffffafa9006db8b0 EFLAGS: 00010286
Jun  4 22:32:45 kernel: [   18.475518] RAX: 8030000000000000 RBX: ffff9f3518871900 RCX: 0000000000000000
Jun  4 22:32:45 kernel: [   18.475544] RDX: 0000000000000022 RSI: 0000000000000000 RDI: 001a8718359fffff
Jun  4 22:32:45 kernel: [   18.475565] RBP: ffffafa9006db920 R08: ffffffffc0750010 R09: 0000000080190018
Jun  4 22:32:45 kernel: [   18.475581] R10: ffffafa9006db8a8 R11: ffffffffc06643c0 R12: 0000000000000002
Jun  4 22:32:45 kernel: [   18.475608] R13: ffff9f350f9146e0 R14: ffff9f357e9cc8c0 R15: 0000000000000000
Jun  4 22:32:45 kernel: [   18.475636] FS:  00007ecb9f1d9700(0000) GS:ffff9f3584100000(0000) knlGS:0000000000000000
Jun  4 22:32:45 kernel: [   18.475664] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
Jun  4 22:32:45 kernel: [   18.475678] CR2: 000000b542a7b000 CR3: 00000005a196a003 CR4: 00000000000606e0
Jun  4 22:32:45 kernel: [   18.475695] Call Trace:
Jun  4 22:32:45 kernel: [   18.475715]  ? 0xffffffffc06611bc
Jun  4 22:32:45 kernel: [   18.475725]  0xffffffffc06611bc
Jun  4 22:32:45 kernel: [   18.475735]  0xffffffffc0663172
Jun  4 22:32:45 kernel: [   18.475752]  0xffffffffa991d931
Jun  4 22:32:45 kernel: [   18.475778]  ? 0xffffffffa9c001b0
Jun  4 22:32:45 kernel: [   18.475793]  ? 0xffffffffa9c001a4
Jun  4 22:32:45 kernel: [   18.475807]  ? 0xffffffffa9c001b0
Jun  4 22:32:45 kernel: [   18.475821]  ? 0xffffffffa98a489d
Jun  4 22:32:45 kernel: [   18.475835]  ? 0xffffffffa9c001a4
Jun  4 22:32:45 kernel: [   18.475847]  ? 0xffffffffa9c001b0
Jun  4 22:32:45 kernel: [   18.475861]  ? 0xffffffffa9c001a4
Jun  4 22:32:45 kernel: [   18.475874]  ? 0xffffffffa9c001b0
Jun  4 22:32:45 kernel: [   18.475887]  ? 0xffffffffa9c001a4
Jun  4 22:32:45 kernel: [   18.475901]  ? 0xffffffffa9c001a4
Jun  4 22:32:45 kernel: [   18.475916]  ? 0xffffffffa991d7d0
Jun  4 22:32:45 kernel: [   18.475931]  0xffffffffa990f998
Jun  4 22:32:45 kernel: [   18.475955]  0xffffffffa991e32c
Jun  4 22:32:45 kernel: [   18.475967]  0xffffffffa990f0f4
Jun  4 22:32:45 kernel: [   18.475976]  0xffffffffa990f4c5
Jun  4 22:32:45 kernel: [   18.475985]  0xffffffffa989a366
Jun  4 22:32:45 kernel: [   18.476001]  0xffffffffa989a695
Jun  4 22:32:45 kernel: [   18.476010]  ? 0xffffffffa989a822
Jun  4 22:32:45 kernel: [   18.476019]  0xffffffffa989a911
Jun  4 22:32:45 kernel: [   18.476028]  ? 0xffffffffa990c565
Jun  4 22:32:45 kernel: [   18.476037]  ? 0xffffffffa9c001a4
Jun  4 22:32:45 kernel: [   18.476047]  ? 0xffffffffa989bc24
Jun  4 22:32:45 kernel: [   18.476055]  0xffffffffa989bc24
Jun  4 22:32:45 kernel: [   18.476064]  0xffffffffa94017b3
Jun  4 22:32:45 kernel: [   18.476077]  ? 0xffffffffa944285a
Jun  4 22:32:45 kernel: [   18.476476]  ? 0xffffffffa9401438
Jun  4 22:32:45 kernel: [   18.476811]  0xffffffffa9c0008c
Jun  4 22:32:45 kernel: [   18.477151] RIP: 0033:0x00007ecba3432eb0
Jun  4 22:32:45 kernel: [   18.477472] Code: 40 00 41 54 55 41 89 d4 53 48 89 f5 89 fb 48 83 ec 10 e8 d3 ef ff ff 48 63 fb 41 89 c0 49 63 d4 48 89 ee b8 2e 00 00 00 0f 05 <48> 3d 00 f0 ff ff 77 1b 44 89 c7 48 89 44 24 08 e8 0b f0 ff ff 48
Jun  4 22:32:45 kernel: [   18.478126] RSP: 002b:00007ecb9f1d7910 EFLAGS: 00000293 ORIG_RAX: 000000000000002e
Jun  4 22:32:45 kernel: [   18.478455] RAX: ffffffffffffffda RBX: 0000000000000008 RCX: 00007ecba3432eb0
Jun  4 22:32:45 kernel: [   18.478779] RDX: 0000000000000000 RSI: 00007ecb9f1d7950 RDI: 0000000000000008
Jun  4 22:32:45 kernel: [   18.479231] RBP: 00007ecb9f1d7950 R08: 0000000000000000 R09: 0000000000000003
Jun  4 22:32:45 kernel: [   18.479641] R10: 0000000000000001 R11: 0000000000000293 R12: 0000000000000000
Jun  4 22:32:45 kernel: [   18.479937] R13: 0000000000000000 R14: 0000000000000000 R15: 000000b52cbd85a8
Jun  4 22:32:45 kernel: [   18.480336] Modules linked in: iptable_nat xt_set xt_AUDIT ipt_REJECT nf_reject_ipv4 iptable_mangle xt_NFQUEUE xt_limit iptable_raw xt_recent ip6table_nat xt_comment ip6t_REJECT nf_reject_ipv6 xt_addrtype xt_mark ip6table_mangle xt_CT ip6table_raw xt_multiport xt_conntrack nf_log_ipv4 nfnetlink_log xt_NFLOG nf_nat_tftp nf_nat_snmp_basic xt_LOG nf_log_ipv6 nf_conntrack_snmp nf_log_common nf_nat_sip nf_nat_pptp nf_nat_irc nf_nat_h323 nf_nat_ftp nf_nat_amanda ts_kmp nf_conntrack_amanda nf_nat nf_conntrack_sane nf_conntrack_tftp nf_conntrack_sip nf_conntrack_pptp nf_conntrack_netlink nf_conntrack_netbios_ns nf_conntrack_broadcast nf_conntrack_irc nf_conntrack_h323 nf_conntrack_ftp nf_conntrack nf_defrag_ipv6 nf_defrag_ipv4 libcrc32c nfnetlink_queue ip6table_filter ip6_tables xt_tcpudp iptable_filter ip_set_hash_ip ip_set quota_v2 quota_tree intel_rapl_msr intel_rapl_common kvm_intel kvm irqbypass crct10dif_pclmul crc32_pclmul ghash_clmulni_intel cirrus drm_kms_helper aesni_intel snd_pcm drm
Jun  4 22:32:45 kernel: [   18.480383]  crypto_simd snd_timer cryptd virtio_rng glue_helper snd rng_core soundcore virtio_console fb_sys_fops 9pnet_virtio sg evdev syscopyarea pcspkr sysfillrect 9pnet sysimgblt virtio_balloon serio_raw button ip_tables x_tables autofs4 ext4 crc32c_generic crc16 mbcache jbd2 hid_generic usbhid hid virtio_net net_failover failover virtio_blk sr_mod cdrom ata_generic ata_piix xhci_pci xhci_hcd libata psmouse crc32c_intel usbcore scsi_mod virtio_pci virtio_ring virtio i2c_piix4 floppy
Jun  4 22:32:45 kernel: [   18.486103] ---[ end trace e4352b4da1b45d4b ]---`

**Comment by anthraxx** [comment]
This output doesn't help too much and I suspect a problem to be in vanilla kernel and not hardened related. Please take the hardened generated config that you were using and use that with a stock vanilla kernel. you may also want to enable DEBUG_INFO and enable more verbose kern messages to see if there is anything meaningful.
In case you can't reproduce it that way in vanilla, you can try to start bisecting the hardened patches one by one and fine the faulty commit -- which i currently still suspect has nothing to do with hardened itself.

**Comment by anthraxx** [comment]
closing for now due to lack of response
