### ISSUE TITLE
Disabling some options

### ISSUE THREAD

**Issue by hyder365** [anthraxx/linux-hardened#45]
I'd like to propose we consider disabling some dangerous, unmaintained options in the kernel that are being brought to light in this oss-sec discussion:

https://www.openwall.com/lists/oss-security/2020/07/28/3
https://www.openwall.com/lists/oss-security/2020/07/29/2

Thank you. (Sorry if this is not the right place to suggest config changes.)

**Comment by tsautereau-anssi** [comment]
So what are those dangerous Kconfig options that should be disabled, precisely?
