### ISSUE TITLE
Question is it advisable to set sysctl value kernel.unprivileged_userns_clone = 1 for Desktop PC usage for using flatpaks & chromium .

### ISSUE THREAD

**Issue by Anish-M-code** [anthraxx/linux-hardened#66]
Hi @anthraxx , total newbie here , Actually in https://wiki.archlinux.org/title/security section Sandboxing Applications , it is mentioned that kernel.unprivileged_userns_clone = 0 is set by default for linux hardened but flatpak , chromium requires kernel.unprivileged_userns_clone = 1 to work properly. so is it advisable to enable it? I want to take advantage of hardened kernel but except this sysctl hardening work.

I have read workarounds ,like using bubblewrap-suid for flatpak and chromium using suid for layer-1 isolation but i have learnt that suid programs are dangerous , i dont know if setting kernel.unprivileged_userns_clone = 1 is more dangerous than using suid , any guidance will be greatly appreciated.

**Comment by Bernhard40** [comment]
Sometimes there is no alternative, i.e. chromium flatpak won't work with bubblewrap-suid. If you run most desktop apps in containers/sandboxes then there may be more security benefits of setting kernel.unprivileged_userns_clone = 1 than the opposite.

**Comment by Anish-M-code** [comment]
Thanks for replying @Bernhard40 , i enabled kernel.unprivileged_userns_clone = 1 in sysctl.conf and using linux hardened but chromium shows ptrace with yama LSM non broker as not present. But when kernel.unprivileged_userns_clone = 0 it shows yama LSM non broker as yes in sandbox status, is this behaviour expected while using linux hardened kernel ?

As far in sysct.conf i have only set kernel.yama.ptrace_scope = 3 and  kernel.unprivileged_userns_clone = 1

![chromium_suid](https://user-images.githubusercontent.com/58029804/159414813-c2f46eec-6c41-4c52-8a03-1e42869e7f79.png)

![usernamespace](https://user-images.githubusercontent.com/58029804/159414839-d0f4c360-3287-4bc7-b8e0-ae30825e1db5.png)
