### ISSUE TITLE
Section mismatch with extra_latent_entropy in v5.1

### ISSUE THREAD

**Issue by tsautereau-anssi** [anthraxx/linux-hardened#7]
[extra_latent_entropy](https://github.com/anthraxx/linux-hardened/commit/88b8d47ec945e80f0a59689466903f88193c7bf2) is marked ``__meminitdata``. Following commit [a9cd410a3d29](https://github.com/torvalds/linux/commit/a9cd410a3d296846a8125aa43d97a573a354c472) ("mm/page_alloc.c: memory hotplug: free pages as higher order") in v5.1, ``static void __init __free_pages_boot_core()`` was changed into ``void __free_pages_core()``, causing the following section mismatch warning at compile time:
```
WARNING: vmlinux.o(.text+0x180fe4): Section mismatch in reference from the function __free_pages_core() to the variable .meminit.data:extra_latent_entropy
The function __free_pages_core() references
the variable __meminitdata extra_latent_entropy.
This is often because __free_pages_core lacks a __meminitdata
annotation or the annotation of extra_latent_entropy is wrong.
```

**Comment by anthraxx** [comment]
Fixed by bcea61f1ed691c9ab26ce9f73e047ac18c38e4a4
