### ISSUE TITLE
unable to disable rds , dccp , sctp , ticp protocols on linux hardened 5.17.15

### ISSUE THREAD

**Issue by evil-user** [anthraxx/linux-hardened#71]
i added rules to disable them in a security.conf inside /etc/modprobe.d/ folder and in /etc/mkinitcpio.conf added line FILES=(/etc/modprobe.d/security.conf) and ran sudo mkinitcpio -P and then rebooted system and verified output using lynis which showed rds , dccp , sctp , ticp not disabled.

the contents of security.conf was copied from https://github.com/Kicksecure/security-misc/blob/master/etc/modprobe.d/30_security-misc.conf

**Comment by anthraxx** [comment]
I assume you are using the packages provided by the Arch repositories. Those actually do not even compile DCCP and SCTP, so the report from lynis seems rather weird:
https://github.com/archlinux/svntogit-packages/blob/packages/linux-hardened/trunk/config#L1577-L1578

I assume you should instead be looking at what and why lynis reports what looks at.

**Comment by evil-user** [comment]
ok sir closing issue.
