### ISSUE TITLE
5.19: Fix needed in checkreqprot removal commit

### ISSUE THREAD

**Issue by hardfalcon** [anthraxx/linux-hardened#74]
In the 5.19 branch, commit 180ebcbee0d0535890bfc28c626d16224ab72ed1 needs to be reworked to make the kernel actually compile (at least when rebasing/applying the patchset onto a vanilla 5.19 kernel). These two lines introduced by upstream need to be removed to prevent compilation errors:
https://github.com/anthraxx/linux-hardened/commit/81200b0265b15609dcecf192e3f7fb238ec0d3da#diff-798a64f5b6674cae172dc9699756a73dc22ee04529390eed34f6acf3c5453c08R7296

**Comment by anthraxx** [comment]
fixed in 5.19
