### ISSUE TITLE
Commit "usb: implement dedicated subsystem sysctl tables" broken in 6.5 branch

### ISSUE THREAD

**Issue by hardfalcon** [anthraxx/linux-hardened#87]
Hi, commit 26bf8ab0bccea82bc0793b3c8cceb6e01412a52f "usb: implement dedicated subsystem sysctl tables" in the 6.5 branch is broken because the functions `register_sysctl_table()` and `unregister_sysctl_table()` were removed in mainline kernel 6.5:

https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit?id=b8cbc0855a22fe386c704ee29fb21282f999b995

**Comment by anthraxx** [comment]
I'm aware but thanks for reporting :) I was using GH to transfer some work between the pc I used for porting the code and a new build machine I wanted to use for testing.
