### ISSUE TITLE
is this really the maintained version?

### ISSUE THREAD

**Issue by secretmango** [anthraxx/linux-hardened#88]
Is there a repo that has updated configs?

I see this has lots of open PRs that are not really used.

**Comment by spignelon** [comment]
@firefoxlover It is the maintained repo, you will have to check the branches of this repository for latest updates on different kernel version/branches: https://github.com/anthraxx/linux-hardened/branches/active

**Comment by secretmango** [comment]
Thanks, I think leaving it open as an FAQ makes sense?

**Comment by spignelon** [comment]
Not really
