### ISSUE TITLE
4.14 patches?

### ISSUE THREAD

**Issue by commonuserlol** [anthraxx/linux-hardened#94]
Hey, I would cherry pick some patches for 4.14. Yes, it reached EOL, but OpenELA now supporting kernel (mainly backporting changes from 4.19). Is master branch for 4.14?

**Comment by celunah** [comment]
I checked Makefile, it reads 5.12-rc3, so it is not.

**Comment by anthraxx** [comment]
You need to check the tags and releases, not the master branch.
You can find it at https://github.com/anthraxx/linux-hardened/releases/tag/4.14.336-hardened1 but I do not recommend using 4.14 for anything nowadays, ots an old unsupported tree and 4.14 shouldn't be used anymore.
